# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180621_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
